const { signupOwner, loginOwner, ownerProfile, checkOwner, updateOwnerProfile, ownerLogout, activateOwner, deactivateOwner, changePasswordowner, ownerForgotPassword, ownerResetPassword, getAllOwners, deleteOwnAccount, confirmBookingByOwner, getPendingBookingsForOwner, sendConfirmationRequest } = require('../../controller/ownerController')
const { adminAuth } = require('../../middlewares/adminAuth')
const { ownerAuth } = require('../../middlewares/ownerAuth')
const { userAuth } = require('../../middlewares/userAuth')
const ownerRouter = require('express').Router()

ownerRouter.post("/owner-signup", signupOwner)
ownerRouter.post("/owner-login", loginOwner)
ownerRouter.get("/get-all-owner", adminAuth, getAllOwners)
ownerRouter.get("/owner-profile", ownerAuth, ownerProfile)
ownerRouter.get("/check-owner", ownerAuth, checkOwner)
ownerRouter.delete("/delete-own-account", deleteOwnAccount)
ownerRouter.put("/update-owner-profile", ownerAuth, updateOwnerProfile)
ownerRouter.post("/owner-logout", ownerAuth, ownerLogout)
ownerRouter.post("/activate-owner/:ownerId", adminAuth, activateOwner)
ownerRouter.post("/deactivate-owner/:ownerId", adminAuth, deactivateOwner)
ownerRouter.post("/change-owner-password", ownerAuth, changePasswordowner)
ownerRouter.post("/forgot-owner-password", ownerForgotPassword)
ownerRouter.post("/reset-owner-password/:token", ownerResetPassword)
ownerRouter.post("/confirm/:requestId", ownerAuth, confirmBookingByOwner)
ownerRouter.get("/pending-requests", ownerAuth, getPendingBookingsForOwner)
ownerRouter.post("/send-request", userAuth, sendConfirmationRequest)

module.exports = ownerRouter